steps:
  - label: ":go: build linux"
    artifact_paths: "./dist/dbp-linux-amd64"
    command: "CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/dbp-linux-amd64"
    plugins:
      - docker#v2.1.0:
          image: "golang"
  - label: ":go: build darwin"
    artifact_paths: "./dist/dbp-darwin-amd64"
    command: "CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o dist/dbp-darwin-amd64"
    plugins:
      - docker#v2.1.0:
          image: "golang"
  - label: "publish docs"
    branches: "v*.*.*"
    agents:
      queue: "deploy"
    command: |
      echo "--- Installing mkdocs"
      rm -rf .venv
      python3 -mvenv .venv
      .venv/bin/pip install mkdocs-material pygments pymdown-extensions
      echo "+++ Deploying site"
      .venv/bin/mkdocs gh-deploy --force
